<?php
/**
 * SearchApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Nuitee
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Lite API
 *
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Nuitee\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Nuitee\ApiException;
use Nuitee\Configuration;
use Nuitee\HeaderSelector;
use Nuitee\ObjectSerializer;

class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getHotelRates' => [
            'application/json',
        ],
        'getHotels' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        Configuration $config = null,
        ClientInterface $client = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getHotelRates
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotelRates'] to see the possible values for this operation
     *
     * @throws \Nuitee\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Nuitee\Model\GetHotelRatesResponse|\Nuitee\Model\GetHotelRates204Response|\Nuitee\Model\GetHotelRates400Response
     */
    public function getHotelRates($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotelRates'][0])
    {
        list($response) = $this->getHotelRatesWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType);
        return $response;
    }

    /**
     * Operation getHotelRatesWithHttpInfo
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotelRates'] to see the possible values for this operation
     *
     * @throws \Nuitee\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Nuitee\Model\GetHotelRatesResponse|\Nuitee\Model\GetHotelRates204Response|\Nuitee\Model\GetHotelRates400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHotelRatesWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotelRates'][0], \Nuitee\RequestOptions $requestOptions = new \Nuitee\RequestOptions())
    {
        $request = $this->getHotelRatesRequest($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (
                    ($e->getCode() == 401 || $e->getCode() == 403) &&
                    !empty($this->getConfig()->getAccessToken()) &&
                    $requestOptions->shouldRetryOAuth()
                ) {
                    return $this->getHotelRatesWithHttpInfo(
                        $hotel_ids,
                        $checkin,
                        $checkout,
                        $guest_nationality,
                        $currency,
                        $adults,
                        $children,
                        $guest_id,
                        $contentType,
                        $requestOptions->setRetryOAuth(false)
                    );
                }

                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Nuitee\Model\GetHotelRatesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Nuitee\Model\GetHotelRatesResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Nuitee\Model\GetHotelRatesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 204:
                    if ('\Nuitee\Model\GetHotelRates204Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Nuitee\Model\GetHotelRates204Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Nuitee\Model\GetHotelRates204Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Nuitee\Model\GetHotelRates400Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Nuitee\Model\GetHotelRates400Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Nuitee\Model\GetHotelRates400Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Nuitee\Model\GetHotelRatesResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nuitee\Model\GetHotelRatesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 204:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nuitee\Model\GetHotelRates204Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nuitee\Model\GetHotelRates400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getHotelRatesAsync
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotelRates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHotelRatesAsync($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotelRates'][0])
    {
        return $this->getHotelRatesAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getHotelRatesAsyncWithHttpInfo
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotelRates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHotelRatesAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotelRates'][0])
    {
        $returnType = '\Nuitee\Model\GetHotelRatesResponse';
        $request = $this->getHotelRatesRequest($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getHotelRates'
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotelRates'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getHotelRatesRequest($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotelRates'][0])
    {

        // verify the required parameter 'hotel_ids' is set
        if ($hotel_ids === null || (is_array($hotel_ids) && count($hotel_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter hotel_ids when calling getHotelRates'
            );
        }

        // verify the required parameter 'checkin' is set
        if ($checkin === null || (is_array($checkin) && count($checkin) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter checkin when calling getHotelRates'
            );
        }

        // verify the required parameter 'checkout' is set
        if ($checkout === null || (is_array($checkout) && count($checkout) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter checkout when calling getHotelRates'
            );
        }

        // verify the required parameter 'guest_nationality' is set
        if ($guest_nationality === null || (is_array($guest_nationality) && count($guest_nationality) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter guest_nationality when calling getHotelRates'
            );
        }

        // verify the required parameter 'currency' is set
        if ($currency === null || (is_array($currency) && count($currency) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter currency when calling getHotelRates'
            );
        }

        // verify the required parameter 'adults' is set
        if ($adults === null || (is_array($adults) && count($adults) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter adults when calling getHotelRates'
            );
        }




        $resourcePath = '/hotels/rates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $hotel_ids,
            'hotelIds', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkin,
            'checkin', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkout,
            'checkout', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_nationality,
            'guestNationality', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency,
            'currency', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $adults,
            'adults', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $children,
            'children', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_id,
            'guestId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getHotels
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotels'] to see the possible values for this operation
     *
     * @throws \Nuitee\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Nuitee\Model\GetHotelsResponse|\Nuitee\Model\GetHotels204Response|\Nuitee\Model\GetHotels400Response|\Nuitee\Model\GetHotels401Response
     */
    public function getHotels($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotels'][0])
    {
        list($response) = $this->getHotelsWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType);
        return $response;
    }

    /**
     * Operation getHotelsWithHttpInfo
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotels'] to see the possible values for this operation
     *
     * @throws \Nuitee\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Nuitee\Model\GetHotelsResponse|\Nuitee\Model\GetHotels204Response|\Nuitee\Model\GetHotels400Response|\Nuitee\Model\GetHotels401Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHotelsWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotels'][0], \Nuitee\RequestOptions $requestOptions = new \Nuitee\RequestOptions())
    {
        $request = $this->getHotelsRequest($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                if (
                    ($e->getCode() == 401 || $e->getCode() == 403) &&
                    !empty($this->getConfig()->getAccessToken()) &&
                    $requestOptions->shouldRetryOAuth()
                ) {
                    return $this->getHotelsWithHttpInfo(
                        $hotel_ids,
                        $checkin,
                        $checkout,
                        $currency,
                        $guest_nationality,
                        $adults,
                        $children,
                        $guest_id,
                        $contentType,
                        $requestOptions->setRetryOAuth(false)
                    );
                }

                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Nuitee\Model\GetHotelsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Nuitee\Model\GetHotelsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Nuitee\Model\GetHotelsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 204:
                    if ('\Nuitee\Model\GetHotels204Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Nuitee\Model\GetHotels204Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Nuitee\Model\GetHotels204Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Nuitee\Model\GetHotels400Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Nuitee\Model\GetHotels400Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Nuitee\Model\GetHotels400Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Nuitee\Model\GetHotels401Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Nuitee\Model\GetHotels401Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Nuitee\Model\GetHotels401Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Nuitee\Model\GetHotelsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nuitee\Model\GetHotelsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 204:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nuitee\Model\GetHotels204Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nuitee\Model\GetHotels400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Nuitee\Model\GetHotels401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getHotelsAsync
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotels'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHotelsAsync($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotels'][0])
    {
        return $this->getHotelsAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getHotelsAsyncWithHttpInfo
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotels'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHotelsAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotels'][0])
    {
        $returnType = '\Nuitee\Model\GetHotelsResponse';
        $request = $this->getHotelsRequest($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getHotels'
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getHotels'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getHotelsRequest($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['getHotels'][0])
    {

        // verify the required parameter 'hotel_ids' is set
        if ($hotel_ids === null || (is_array($hotel_ids) && count($hotel_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter hotel_ids when calling getHotels'
            );
        }

        // verify the required parameter 'checkin' is set
        if ($checkin === null || (is_array($checkin) && count($checkin) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter checkin when calling getHotels'
            );
        }

        // verify the required parameter 'checkout' is set
        if ($checkout === null || (is_array($checkout) && count($checkout) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter checkout when calling getHotels'
            );
        }

        // verify the required parameter 'currency' is set
        if ($currency === null || (is_array($currency) && count($currency) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter currency when calling getHotels'
            );
        }

        // verify the required parameter 'guest_nationality' is set
        if ($guest_nationality === null || (is_array($guest_nationality) && count($guest_nationality) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter guest_nationality when calling getHotels'
            );
        }

        // verify the required parameter 'adults' is set
        if ($adults === null || (is_array($adults) && count($adults) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter adults when calling getHotels'
            );
        }




        $resourcePath = '/hotels';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $hotel_ids,
            'hotelIds', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkin,
            'checkin', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkout,
            'checkout', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency,
            'currency', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_nationality,
            'guestNationality', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $adults,
            'adults', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $children,
            'children', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_id,
            'guestId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
