<?php
/**
 * Book401ResponseDataCancellationPoliciesTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nuitee
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Lite API
 *
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Nuitee\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * Book401ResponseDataCancellationPoliciesTest Class Doc Comment
 *
 * @category    Class
 * @description Book401ResponseDataCancellationPolicies
 * @package     Nuitee
 */
class Book401ResponseDataCancellationPoliciesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Book401ResponseDataCancellationPolicies"
     */
    public function testBook401ResponseDataCancellationPolicies()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cancel_policy_infos"
     */
    public function testPropertyCancelPolicyInfos()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hotel_remarks"
     */
    public function testPropertyHotelRemarks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refundable_tag"
     */
    public function testPropertyRefundableTag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
