<?php
/**
 * GetHotel400ResponseDataInnerHotelPhotosInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Nuitee
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * Lite API
 *
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Nuitee\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetHotel400ResponseDataInnerHotelPhotosInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetHotel400ResponseDataInnerHotelPhotosInner
 * @package     Nuitee
 */
class GetHotel400ResponseDataInnerHotelPhotosInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetHotel400ResponseDataInnerHotelPhotosInner"
     */
    public function testGetHotel400ResponseDataInnerHotelPhotosInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url_max300"
     */
    public function testPropertyUrlMax300()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url_original"
     */
    public function testPropertyUrlOriginal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url_square60"
     */
    public function testPropertyUrlSquare60()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
